# Generated by Django 5.0.1 on 2024-01-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Наименование задачи"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Выполнена"),
                ),
            ],
        ),
    ]
